### ISSUE TITLE
问题反馈：刷新文档会重复出现属性面板

### ISSUE THREAD

**Issue by zzz51522** [InEase/SiYuan-Attributes-Panel#1]
开发者你好~
这个插件非常实用，解决了我使用思源笔记管理剪藏资料时查看属性信息的需求。但是在实际使用中发现一个小问题，辛苦您看一下。

如标题所写：在对文档执行刷新操作后，属性面板会多显示一个同样的面板，刷新一次就多显示一个。只有重新打开文档后，才能消除多显示的面板。

思源笔记版本： v2.11.4

https://github.com/InEase/SiYuan-Attributes-Panel/assets/145221733/1c703097-cea0-491a-872f-2fcc7e6dedc5

**Comment by InEase** [comment]
我去，bu zhi

**Comment by InEase** [comment]
我去，误触了（（

**Comment by InEase** [comment]
找到问题了，每次刷新的时候都会emit一次`loaded-protyle-static`事件，感觉是by design

https://github.com/siyuan-note/siyuan/blob/cb6a843cd9570b443b4b0775660b1cd49353951a/app/src/protyle/util/onGet.ts#L260

不过其实之前的代码里面做了一次检测，如果已经有面板就不插入了，但是因为query写错了，写成了id `#`导致没生效，今天修复

https://github.com/InEase/SiYuan-Attributes-Panel/blob/b7725cc1e5b800195f3051fc69451d3dd2d1011d/src/index.ts#L38

**Comment by InEase** [comment]
先推一版更新上去了，另外两个都是大问题，比较难搞qaq

**Comment by zzz51522** [comment]
> 找到问题了，每次刷新的时候都会emit一次`loaded-protyle-static`事件，感觉是by design
> 
> https://github.com/siyuan-note/siyuan/blob/cb6a843cd9570b443b4b0775660b1cd49353951a/app/src/protyle/util/onGet.ts#L260
> 
> 不过其实之前的代码里面做了一次检测，如果已经有面板就不插入了，但是因为query写错了，写成了id `#`导致没生效，今天修复
> 
> https://github.com/InEase/SiYuan-Attributes-Panel/blob/b7725cc1e5b800195f3051fc69451d3dd2d1011d/src/index.ts#L38

好的，辛苦啦，非常感谢~
